### ISSUE TITLE
Train时候报错。  开发者的paddle是啥版本？

### ISSUE THREAD

**Issue by yinpub** [Rebeccalomi/MICCAI2023-STAGE_Task1#1]
我在训练的时候，前几个iter还没事，一段时间后会出错。我怀疑是我paddle版本的问题。开发者开发时的版本是多少呢？

**Comment by Rebeccalomi** [comment]
十分抱歉，没能及时查看邮箱，虽然不知道问题有没有得到解决，但是还是回复一下，我使用的paddle版本是paddle-gpu 2.3.2，python3.8.0，十分十分抱歉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Rebeccalomi/MICCAI2023-STAGE_Task1"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月10日(星期四) 晚上9:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Rebeccalomi/MICCAI2023-STAGE_Task1] Train时候报错。  开发者的paddle是啥版本？ (Issue #1)





 
我在训练的时候，前几个iter还没事，一段时间后会出错。我怀疑是我paddle版本的问题。开发者开发时的版本是多少呢？

**Comment by yinpub** [comment]
发现问题了，是因为划分的数据集必须整数。但是数据有301条。去掉那一条就没问题了，
